# create remain
REMAIN_POST_SUCCESS = 55
REMAIN_POST_FAIL = 56
REMAIN_POST_NO_USER = 57
REMAIN_POST_CONDITION_ERROR = 58
REMAIN_POST_EXITED = 59

REMAIN_DELETE_SUCCESS = 60
REMAIN_DELETE_FAIL = 61
REMAIN_DELETE_NO_USER = 62
REMAIN_DELETE_NO_REMAIN = 63
REMAIN_DELETE_CONDITION_ERROR = 64