# create clockIn
REMAIN_POST_SUCCESS = "创建提醒成功"
REMAIN_POST_FAIL = "创建提醒失败"
REMAIN_POST_NO_USER = "没有该用户"
REMAIN_POST_CONDITION_ERROR = "请求参数错误"
REMAIN_POST_EXITED = "已经存在该提醒"

REMAIN_DELETE_SUCCESS = "成功删除提醒"
REMAIN_DELETE_FAIL = "删除提醒失败"
REMAIN_DELETE_NO_USER = "没有该用户"
REMAIN_DELETE_NO_REMAIN = "没有该提醒"
REMAIN_DELETE_CONDITION_ERROR = "请求参数错误"