# get todo
TODO_GET_SUCCESS = 19
TODO_GET_FAIL = 20
TODO_GET_EMPTY = 21
TODO_GET_NOT_DEFAULT_TODO_SET = 22

# create todo
TODO_POST_SUCCESS = 23
TODO_POST_FAIL = 24
TODO_POST_NO_NAME = 25
TODO_POST_EXITED = 26
TODO_POST_TODO_SET_NOT_EXIT = 27
TODO_POST_NO_TODO_SET_NAME = 28

# update todo
TODO_UPDATE_SUCCESS = 29
TODO_UPDATE_FAIL = 30
TODO_UPDATE_NO_CONDITION = 31
TODO_UPDATE_NO_TODO_SET = 32
TODO_UPDATE_NO_TODO = 33

# delete todo
TODO_DELETE_SUCCESS = 34
TODO_DELETE_FAIL = 35
TODO_DELETE_NO_CONDITION = 36
TODO_DELETE_NO_TODO_SET = 37
TODO_DELETE_NO_TODO = 38