# create clockIn
CLOCK_IN_POST_SUCCESS = 45
CLOCK_IN_POST_FAIL = 46
CLOCK_IN_POST_NO_USER = 47
CLOCK_IN_POST_CONDITION_ERROR = 48
CLOCK_IN_POST_EXITED = 49

CLOCK_IN_DELETE_SUCCESS = 50
CLOCK_IN_DELETE_FAIL = 51
CLOCK_IN_DELETE_NO_USER = 52
CLOCK_IN_DELETE_NO_CLOCK_IN = 53
CLOCK_IN_DELETE_CONDITION_ERROR = 54