# create clockIn
CLOCK_IN_POST_SUCCESS = "创建打卡成功"
CLOCK_IN_POST_FAIL = "创建打卡失败"
CLOCK_IN_POST_NO_USER = "没有该用户"
CLOCK_IN_POST_CONDITION_ERROR = "请求参数错误"
CLOCK_IN_POST_EXITED = "已经存在该打卡"

CLOCK_IN_DELETE_SUCCESS = "成功删除打卡"
CLOCK_IN_DELETE_FAIL = "删除打卡失败"
CLOCK_IN_DELETE_NO_USER = "没有该用户"
CLOCK_IN_DELETE_NO_CLOCK_IN = "没有该打卡"
CLOCK_IN_DELETE_CONDITION_ERROR = "请求参数错误"