# get todoSet
T0DOSET_GET_SUCCESS = 5
TODOSET_GET_FAIL = 6
TODOSET_GET_EMPTY = 7

# create todoSet
TODOSET_POST_SUCCESS = 8
TODOSET_POST_FAIL = 9
TODOSET_NOT_NAME = 10
TODOSET_EXITED = 11
TODOSET_SERVER_ERRR = 12