# get todoSet
T0DO_SET_GET_SUCCESS = 5
TODO_SET_GET_FAIL = 6
TODO_SET_GET_EMPTY = 7

# create todoSet
TODO_SET_POST_SUCCESS = 8
TODO_SET_POST_FAIL = 9
TODO_SET_NOT_NAME = 10
TODO_SET_EXITED = 11
TODO_SET_SERVER_ERRR = 12

# update todoSet
TODO_SET_UPDATE_SUCCESS = 13
TODO_SET_UPDATE_FAIL = 14
TODO_SET_UPDATE_NOT_EXIT = 15

# delete todoSet
TODO_SET_DELETE_SUCCESS = 16
TODO_SET_DELETE_FAIL = 17
TODO_SET_DELETE_NOT_EXIT = 18